In [2]:
import numpy as np

# Creating a 1D array from a list
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", array_1d)

1D Array: [1 2 3 4 5]


In [3]:
# Creating a 2D array (matrix)
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", array_2d)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [5]:
 #Creating an array of zeros
zeros_array = np.zeros((2, 3))  # 2 rows, 3 columns
print("Array of Zeros:\n", zeros_array)

Array of Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# Creating an array of ones
ones_array = np.ones((3, 2))  # 3 rows, 2 columns
print("Array of Ones:\n", ones_array)

Array of Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [7]:
# Creating an array with a range of values
range_array = np.arange(0, 10, 2)  # Start, stop, step
print("Range Array:", range_array)

Range Array: [0 2 4 6 8]


In [9]:
#2.Array Indexing


# Accessing elements
print("First element of 1D array:", array_1d[0])
print("Element at (1, 2) in 2D array:", array_2d[1, 2])  # Row 1, Column 2

First element of 1D array: 1
Element at (1, 2) in 2D array: 6


In [10]:
# Slicing arrays
print("Slicing 1D array (first three elements):", array_1d[:3])
print("Slicing 2D array (first row):", array_2d[0, :])
print("Slicing 2D array (first two rows, first two columns):\n", array_2d[:2, :2])

Slicing 1D array (first three elements): [1 2 3]
Slicing 2D array (first row): [1 2 3]
Slicing 2D array (first two rows, first two columns):
 [[1 2]
 [4 5]]


In [11]:
#Mathematical Operations


# Element-wise operations
array_a = np.array([1, 2, 3])
array_b = np.array([4, 5, 6])

In [12]:
# Addition
sum_array = array_a + array_b
print("Sum of Arrays:", sum_array)

Sum of Arrays: [5 7 9]


In [13]:
# Multiplication
product_array = array_a * array_b
print("Product of Arrays:", product_array)

Product of Arrays: [ 4 10 18]


In [14]:
# Universal functions (ufuncs)
squared_array = np.square(array_a)
print("Squared Array:", squared_array)

Squared Array: [1 4 9]


In [15]:
# Statistical operations
mean_value = np.mean(array_a)
print("Mean of Array A:", mean_value)

Mean of Array A: 2.0


In [16]:
# Standard deviation
std_dev = np.std(array_a)
print("Standard Deviation of Array A:", std_dev)

Standard Deviation of Array A: 0.816496580927726


In [17]:
# Reshaping an array
reshaped_array = np.arange(12).reshape(3, 4)  # 3 rows, 4 columns
print("Reshaped Array:\n", reshaped_array)

Reshaped Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [19]:
# Concatenating arrays
array_c = np.array([[7, 8, 9,10]])
concatenated_array = np.concatenate((reshaped_array, array_c), axis=0)  # Concatenate along rows
print("Concatenated Array:\n", concatenated_array)

Concatenated Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 7  8  9 10]]


In [20]:
# Broadcasting example
array_x = np.array([[1, 2, 3], [4, 5, 6]])
array_y = np.array([10, 20, 30])  # 1D array

# Adding a 1D array to a 2D array
broadcasted_sum = array_x + array_y
print("Broadcasted Sum:\n", broadcasted_sum)


Broadcasted Sum:
 [[11 22 33]
 [14 25 36]]


In [21]:
# Saving an array to a text file
np.savetxt('array_data.txt', array_1d)

# Loading an array from a text file
loaded_array = np.loadtxt('array_data.txt')
print("Loaded Array from File:", loaded_array)


Loaded Array from File: [1. 2. 3. 4. 5.]
